### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by okayu-331** [okayu-331/furima_28788#10]
## URL
https://furima-28788.herokuapp.com/

## Basic認証のIDとパスワード
ID | パスワード
------------ | -------------
admin |  2828

## 出品者用のメールアドレスとパスワード
メールアドレス | パスワード
------------ | ------------- 
user1@example.com | pass1111

## 購入者用のメールアドレスとパスワード
メールアドレス | パスワード
------------ | ------------- 
user2@example.com | pass2222

## 購入用カードの番号・期限・セキュリティコード
カード番号 | 期限 | セキュリティコード
------------ | ------------- | ---- 
4242424242424242 | 3/23 | 123

**Comment by rumaruma0408** [comment]
okayu-331 さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**

**Comment by okayu-331** [comment]
ご確認ありがとうございました！
